First lets do a node-based FFT, based on these basis functions:


$s^k_i = sin(2 \pi k x_i)$
$c^k_i = cos(2 \pi k x_i)$

where $x_i = i / N$ for $i \in [0, \dots, N-1]$

In [1]:
import numpy as np
import numpy.fft as fft

In [2]:
# Number of points in domain - don't forget x=1 is periodic wrap of x=0
N=8

In [3]:
# Create the node-based functions
x_node = np.linspace(0,1-1/N,N)  # x node values from 0 ... not including 1
basis_k = np.zeros((N,N))  # basis functions
basis_k[:,0] = np.ones(N)  # k=0 mode
key_k = ['c0']  # labels for modes
# Fill in sin/cos modes for k between 0 and N/2
for k in range(1,int(N/2)):
    key_k.append(f's{k}')
    key_k.append(f'c{k}')
    basis_k[:,2*k-1] = np.sin(2*np.pi*k*x_node)
    basis_k[:,2*k] = np.cos(2*np.pi*k*x_node)
basis_k[:,N-1] = 1 - 2*np.mod(np.array(range(0,N)),2)  # +1/-1 highest mode
key_k.append(f'c{N-1}') 

In [4]:
key_k

['c0', 's1', 'c1', 's2', 'c2', 's3', 'c3', 'c7']

In [5]:
# Look at the fft of these
xhat = fft.fft(basis_k.T)  # FFT operates on rows, apparently
# xhat = np.round(xhat,15)
xhat = np.round(fft.fftshift(xhat, axes=1),14)
xhat

array([[ 0.+0.j,  0.-0.j,  0.-0.j,  0.-0.j,  8.+0.j,  0.+0.j,  0.+0.j,
         0.+0.j],
       [ 0.+0.j,  0.-0.j,  0.+0.j, -0.+4.j,  0.+0.j, -0.-4.j,  0.-0.j,
         0.+0.j],
       [-0.+0.j, -0.-0.j,  0.-0.j,  4.+0.j, -0.+0.j,  4.-0.j,  0.+0.j,
        -0.+0.j],
       [ 0.+0.j,  0.+0.j, -0.+4.j,  0.-0.j,  0.+0.j,  0.+0.j, -0.-4.j,
         0.-0.j],
       [ 0.+0.j,  0.+0.j,  4.+0.j, -0.+0.j, -0.+0.j, -0.-0.j,  4.-0.j,
         0.-0.j],
       [ 0.+0.j, -0.+4.j,  0.-0.j,  0.+0.j, -0.+0.j,  0.-0.j,  0.+0.j,
        -0.-4.j],
       [ 0.+0.j,  4.+0.j, -0.-0.j,  0.+0.j, -0.+0.j,  0.-0.j, -0.+0.j,
         4.-0.j],
       [ 8.+0.j,  0.-0.j,  0.-0.j,  0.-0.j,  0.+0.j,  0.+0.j,  0.+0.j,
         0.+0.j]])

In [6]:
help(fft.fftshift)

Help on function fftshift in module numpy.fft:

fftshift(x, axes=None)
    Shift the zero-frequency component to the center of the spectrum.
    
    This function swaps half-spaces for all axes listed (defaults to all).
    Note that ``y[0]`` is the Nyquist component only if ``len(x)`` is even.
    
    Parameters
    ----------
    x : array_like
        Input array.
    axes : int or shape tuple, optional
        Axes over which to shift.  Default is None, which shifts all axes.
    
    Returns
    -------
    y : ndarray
        The shifted array.
    
    See Also
    --------
    ifftshift : The inverse of `fftshift`.
    
    Examples
    --------
    >>> freqs = np.fft.fftfreq(10, 0.1)
    >>> freqs
    array([ 0.,  1.,  2.,  3.,  4., -5., -4., -3., -2., -1.])
    >>> np.fft.fftshift(freqs)
    array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])
    
    Shift the zero-frequency component only along the second axis:
    
    >>> freqs = np.fft.fftfreq(9, d=1./9).reshape(