In [1]:
import os.path
from scipy import *
import numpy as np
from numpy import *
from numpy import linalg as LA
from scipy import linalg as LA2
import sympy as sympy
import sys as sys
import time
import matplotlib.pyplot as plt
import itertools as it
from IPython.core.display import HTML


sys.path.append('/Users/sashacurcic/SashasDirectory/ANAG/FV_MG/')
from Modules import BasicTools as BT
from Modules import WaveTools as WT
from Modules import PlotTools as PT
from Modules import FFTTools as FFTT
from Modules import OperatorTools as OT
from Modules import GridTransferTools as GTT
from Modules import TestTools as TT
from Modules import SolverTools as ST
from Modules import WaveformTools as WFT

display(HTML("<style>pre { white-space: pre !important; }</style>"))
np.set_printoptions( linewidth = 10000, threshold = 100000)

In [2]:
nh_min = 8
refCells = 4
refRatio = 2

In [3]:
omega = BT.Grid(nh_min)
finehalf = list(np.arange(refCells))
# finehalf = list(np.arange(int(nh / refRatio)) + int(nh / refRatio))
# print(finehalf)
omega.AddPatch(refRatio, finehalf)
nh_max = omega.nh_max
degFreed = omega.degFreed
waves = WT.MakeWaves(omega)
# PT.PlotWaves(omega, waves = waves)
t = 0
# print(waves)


In [4]:
# ----------------------------------------------------------------------------------------------------------------
# Function: FindSelect
# ----------------------------------------------------------------------------------------------------------------
# By: Sasha Curcic
#
# This function
# ----------------------------------------------------------------------------------------------------------------
# Input:
#
# omega               BT.Grid             Grid object
# waves               (N x M) real        Matrix of wave vectors
# ----------------------------------------------------------------------------------------------------------------
# Output:
#
# WTWinv              (M x M) real        A positive non negative number given by the user
# ----------------------------------------------------------------------------------------------------------------

In [5]:
def FindSelect(omega, waves):
    errorLoc = 'ERROR:\nOperatorTools:\nFindSelect:\n'
    nhs = omega.nh
    nh_min = omega.nh_min
    nh_max = omega.nh_max
    nh_mid = nhs[-2]
    degFreed = omega.degFreed
    
    # Create selection matrix to be filled.
    fixWaves = np.zeros((nh_max, degFreed), float)

    # Calculate number of modes needed in addition to smooth modes and first oscillatory mode.
    addOn = degFreed - nh_mid - 1
    
    # Calculate start and stop indices of modes through which to iterate and test.
    mode = nh_mid + 1
    wavenum = int(mode / 2)
    iters = int((nh_max / 2))
    j = mode
    
    np.fill_diagonal(fixWaves[:, :-addOn], 1) # This won't work for low degFreed.
    print(fixWaves)
    # Iterate through number of wavenumbers left
    
    
    
#     span = min(nh_mid + 2, degFreed)
#     span0 = span
    print('\n')
    for i in range(wavenum + 1, iters):
        fixWavesTemp = fixWaves + 0
#         span = span + 1
        print('Iteration: ' + str(i) + '\n')
        # If any more wavenumbers are needed, otherwise, stop the outermost for loop.
        if (addOn > 0):
            if (addOn % 2 == 1):
                fixWavesTemp[-1, -1] = 1
                addOn = addOn - 1
                # mode = mode + 1
            else:
                nullsize = 1
#                 span = span + 1
                while (nullsize > 0):
                    fixWavesTemp = fixWaves + 0
                    fixWavesTemp[mode, j] = 1
                    fixWavesTemp[mode + 1, j + 1] = 1
                    print('TESTING MODES ' + str(mode) + ' & ' + str(mode + 1) + ':\n')
                    print('Test Selection Matrix:')
                    print(fixWavesTemp)
                    print('')
                    wavesTemp = waves @ fixWavesTemp
#                     WTW = wavesTemp.transpose() @ wavesTemp
#                     eigvals, eigvecs = LA.eig(WTW)
#                     eigvals = abs(np.round(eigvals, 14))
                    print('Nullspace of Modes Selected:')
                    nullspace = LA2.null_space(wavesTemp)
                    nullsize = np.shape(nullspace)[1]
                    print(nullspace)
                    print('')
                    print('Size of Nullspace: ' + str(nullsize) + '\n')
                    # span0 = LA.matrix_rank(wavesTemp, tol = 1e-11)#degFreed - len(np.where(eigvals == 0)[0])
                    # cond = #any(eigvals == 0)

                    # ADD AN ERROR CATCH HERE FOR IN CASE YOU CAN'T MANAGE TO SPAN THE SPACE!!!
                    mode = mode + 2
                j = j + 2
                addOn = addOn - 2
            fixWaves = fixWavesTemp
        else:
            break
        print('Successful Matrix Selected:')
        print(fixWaves)
        print('\n')
#     if (degFreed < nh[])
    print('')
    print('Final Selection Matrix:')
    print(fixWaves)
    return fixWaves

In [6]:
# def FindSelect(omega, waves):
#     errorLoc = 'ERROR:\nOperatorTools:\nFindNullspace:\n'
#     levels = omega.levels
#     alias = omega.alias
#     nh_max = omega.nh_max
#     degFreed = omega.degFreed# [::-1][0]
#     fixWaves = np.zeros((nh_max, degFreed), float)
#     nh_min = omega.nh_min
#     nhs = omega.nh
#     nh_mid = nhs[-2]
#     hs = omega.h

#     addOn = degFreed - nh_mid# - 2
    
#     iters = nh_max
#     # mode is the index 
    
#     np.fill_diagonal(fixWaves[:, :-addOn], 1) # This won't work for low degFreed.
#     print(fixWaves)
#     # Iterate through number of wavenumbers left
#     addOn = addOn
#     mode = nh_mid
#     # wavenum = int(mode / 2)
#     print(mode, iters)
#     print('START')
#     j = mode# wavenum
#     span = min(nh_mid, degFreed)
#     span0 = span
#     print('addOn:', addOn)
#     print('')
#     for i in range(mode, iters):
#         print('interation:', i)
#         fixWavesTemp = fixWaves + 0
#         span = span + 1
#         print('spans outer:', span, span0)
        
#         print('addOn Before:', addOn)
#         # If any more wavenumbers are needed, otherwise, stop the outermost for loop.
#         print('spans mid:', span, span0)
#         while (span != span0):
#             fixWavesTemp = fixWaves + 0
#             fixWavesTemp[mode, j] = 1
#             print(mode, j)
#             print(fixWavesTemp)
#             wavesTemp = waves @ fixWavesTemp
#             WTW = wavesTemp.transpose() @ wavesTemp
#             eigvals, eigvecs = LA.eig(WTW)
#             eigvals = abs(np.round(eigvals, 14))
#             span0 = degFreed - len(np.where(eigvals == 0)[0])
#             cond = any(eigvals == 0)
#             print(eigvals)
#             print('spans inner:', span, span0)
#             # ADD AN ERROR CATCH HERE FOR IN CASE YOU CAN'T MANAGE TO SPAN THE SPACE!!!
#             mode = mode + 1
#         j = j + 1
#         addOn = addOn - 1
#         fixWaves = fixWavesTemp
#         print(fixWaves)
#         print('addOn After:', addOn)
#         print9('')
# #     if (degFreed < nh[])
#     print('END')
#     print('')
#     print(fixWaves)
#     return fixWaves

In [7]:
fixWaves = FindSelect(omega, waves)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Iteration: 5

Successful Matrix Selected:
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.

In [8]:
for i in range(2, 6):
    print(i)

2
3
4
5


In [9]:
a = 0
A = np.asarray([[1, 1, 0, 0, a], [3, 3, 0, 0, a], [0, 0, 1, 0, a], [0, 0, 1, 0, a], [0, 0, 0, 0, a], [0, 0, 0, 0, a]])
nullspace = LA2.null_space(A, rcond = 1e-9)
rank = LA.matrix_rank(A, tol = 1e-11)
print(A)
print(type(A))
print(nullspace)
print(rank)

[[1 1 0 0 0]
 [3 3 0 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
<class 'numpy.ndarray'>
[[-0.70710678  0.          0.        ]
 [ 0.70710678  0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          1.        ]
 [ 0.          1.          0.        ]]
2
